name: React Native CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version

      - name: Install dependencies
        run: |
          npm install
          cd ios && pod install && cd ..

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run ESLint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Jest tests
        run: npm test

  bundle:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Android Bundle
        run: |
          cd android
          ./gradlew bundleRelease

      - name: Build iOS Bundle
        run: |
          cd ios
          xcodebuild -scheme YourAppScheme archive -archivePath $PWD/build/YourApp.xcarchive

  android-build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install
          cd ios && pod install && cd ..

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

  ios-build:
    runs-on: macos-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install
          cd ios && pod install && cd ..

      - name: Build iOS app
        run: |
          cd ios
          xcodebuild -scheme YourAppScheme archive -archivePath $PWD/build/YourApp.xcarchive
